import React from 'react';
import './globals.css';
import { Navbar } from '@/components/Navbar';
import { StateContext } from '../context/StateContext'
//import AuthContextProvider from './context/AuthContext';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <Navbar />
          {children}
      </body>
    </html>
  );
}
